-- table users

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255),
    country ENUM('US', 'CO', 'TN') NOT NULL DEFAULT 'US'
);